apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.general.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.general.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.general.name }}
    spec:
      containers:
        - name: {{ .Values.general.name }}
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          ports:
            - containerPort: {{ .Values.general.port }}
          imagePullPolicy: Always