kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.general.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: {{ .Values.general.port }}
      nodePort: 30000
  selector:
    app: {{ .Values.general.name }}
  type: NodePort